name: Android CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build (e.g. v1.5.0)'
        required: true
        default: 'v1.5.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload AAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: serialport-aar
          path: serialport/build/outputs/aar/*.aar
