name: Android CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build (e.g. 1.5.0)'
        required: true
        default: '1.5.0'  # 注意这里使用不带v的标签名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    with:
      repository: 'Acccord/AndroidSerialPort'  # 直接引用原始仓库
      ref: 'refs/tags/1.5.0'
      token: ${{ secrets.GITHUB_TOKEN }}  # 自动拥有读取权限

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      
      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: serialport-aar
          path: serialport/build/outputs/aar/*.aar
